---
- hosts: sspservers
  tasks:
    - name: install PHP dependencies
      apt: pkg={{ item }} state=present install_recommends=no
      with_items:
        - libapache2-mod-php5
        - php-openid
        - php-pear
        - php-xml-parser
        - php5-curl
        - php5-gmp
        - php5-mcrypt
        - php5-readline
      become: true
    - name: checkout SSP
      git: 
        repo: "{{ ssp_repo_url }}"
        dest: "{{ ssp_path }}"
        version: "{{ ssp_repo_version }}"
        accept_hostkey: yes
      become: yes
    - name: download Composer
      get_url: url=https://getcomposer.org/installer dest={{ ssp_path }}/composer-installer validate_certs=no
      become: yes
    - name: install Composer
      command: php -f {{ ssp_path }}/composer-installer -- --install-dir={{ ssp_path }}
      args:
        creates: "{{ ssp_path }}/composer.phar"
      become: true
    - name: run Composer
      command: php "{{ ssp_path }}/composer.phar" install --no-dev --prefer-dist -o -d "{{ ssp_path }}"
      args:
        creates: "{{ ssp_path }}/vendor/autoload.php"
      become: true
    - name: ensure required SSP dirs exist
      file: path={{ ssp_path }}/{{ item }} state=directory
      with_items:
        - config
        - metadata
        - cert
        - log
      become: yes
    - name: generate sha256 password
      script: files/ssha256pwgen.php {{ ssp_path }} {{ ssp_adminpassword }} >     
        creates="{{ ssp_path }}/config/config.php"
      register: ssp_adminpasswordhash
    - name: generate SSP secret salt
      shell: tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | dd bs=32 count=1 status=none
      args:
        creates: "{{ ssp_path }}/config/config.php"
      register: ssp_secretsalt
    - name: configure SSP
      template: 
        src: templates/config.php.j2
        dest: "{{ ssp_path }}/config/config.php"
        force: no
      become: yes
    - name: add SSP alias to ssl site
      template: 
        src: templates/default-ssl.conf.j2
        dest: /etc/apache2/sites-available/default-ssl.conf
      become: yes
      notify:
        - restart apache
  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
    become: yes